# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b7f0c29ac6b4a918083cbb554f291d675e9acf15398651eeb624b32225cc05b3928cc87770ecb3f3263fc5741133c85bfa2d0d164819c044f2b5a69495f58f96

test:
  secret_key_base: ea2e4bd7c05d449b9b49af3dcfadb94148b631bc7f6216b02a58e82d0fc002401e4bbcbf308fc1c608abc1f1ad306e9c132979226a9ff4f0a6529eb02d881682

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
